hellodjango/urls.py
from django.conf.urls.defaults   import patterns, include, url
from django.contrib              import admin
from django.views.generic.simple import redirect_to

from userena                     import views as userena_views

admin.autodiscover()

urlpatterns = patterns('forum.views',
    (r'^$',                                      'home'),
    (r'^reports/$',                              'reports'),
#   (r'^search/$',                               'search'),
    (r'^subscriptions/$',                        'subscriptions'),

#   Category
    (r'^category/add/$',                         'add'),
    (r'^category/(?P<category_id>\d+)/create/$', 'create'),
#   (r'^category/(?P<category_id>\d+)/merge/$',  'merge'),
    (r'^category/(?P<category_id>\d+)/$',        'category'),

#   Thread
    (r'^thread/(?P<thread_id>\d+)/reply/$',      'reply'),
    (r'^thread/js/$',                            'thread_js'),
    (r'^thread/(?P<thread_id>\d+)/lock/$',       'lock_thread'),
    (r'^thread/(?P<thread_id>\d+)/sticky/$',     'sticky_thread'),
    (r'^thread/(?P<thread_id>\d+)/merge/$',      'merge_thread'),
    (r'^thread/(?P<thread_id>\d+)/move/$',       'move_thread'),
    (r'^thread/(?P<thread_id>\d+)/moderate/$',   'moderate_thread'),
    (r'^thread/(\d+)/report/$',                  'report',
                                                 	 {'object_type': 'thread'}),
    (r'^thread/(\d+)/remove/$',                  'remove',
                                                     {'object_type': 'thread'}),
    (r'^thread/(?P<thread_id>\d+)/$',            'thread',
                                                     {'author_id': "Everyone"}),
	(r'^thread/(?P<thread_id>\d+)/author/(?P<author_id>\d+)/$', 'thread'),

#   Post
    (r'^post/(?P<post_id>\d+)/edit/$',           'edit'),
    (r'^post/(\d+)/report/$',                    'report',
                                                     {'object_type': 'post'}),
    (r'^post/(\d+)/remove/$',                    'remove',
                                                     {'object_type': 'post'}),
    (r'^post/(?P<post_id>\d+)/$',                'post'),

#   User
    (r'^user/js/$',                              'user_js'),
    (r'^user/(?P<user_id>\d+)/threads/$',        'user_content', 
                                                     {'object_type': 'thread'}),
    (r'^user/(?P<user_id>\d+)/posts/$',          'user_content',
                                                     {'object_type': 'post'}),
    (r'^user/(?P<user_id>\d+)/$',                'user'),

#   Accounts
#   (r'^login/$',                                'login'),
#   (r'^logout/$',                               'logout'), 
#   (r'^signup/$',                               'register'),
#	(r'^settings/$',                             'settings'),

    # Redirecting undesired URLs in the userena app to home page
    # and replacing them with such ones as "login" and "logout".
    #
    # <?Pdummy> is there to capture the argument that should not 
    # be passed to the url of redirect_to().
    #
    # Kinda hacky, but gets it done.
    (r'^accounts/login/$',                        userena_views.signin),
    (r'^accounts/logout/$',                      'logout'),
    (r'^accounts/settings/$',                    'settings'),

    url(r'^accounts/$',
        redirect_to, {'url': '/'}),

    url(r'^accounts/signin/$',
        redirect_to, {'url': '/accounts/login/'}),

    url(r'^accounts/signout/$',
        redirect_to, {'url': '/accounts/logout/'}),

    url(r'^accounts/page/(?P<dummy>[0-9]+)/$',
        redirect_to, {'url': '/'}),

    url(r'^accounts/(?P<dummy>(?!login|logout|signup)[\.\w]+)/edit/$',
        redirect_to, {'url': '/'}),

    url(r'^accounts/(?P<dummy>(?!login|logout|signup)[\.\w]+)/$',
        redirect_to, {'url': '/'}),
)

urlpatterns += patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/',     include(admin.site.urls)),
    url(r'^accounts/',  include('userena.urls')),
)

hellodjango/forum/models.py
from datetime                   import datetime

from django.contrib.auth.models	import User
from django.db					import models
from django.db.models.signals   import post_save

from userena.models             import UserenaBaseProfile


# Accessed by UserProfile.get_formatting_buttons_display()
# minus the () for a template
# 
# FORMATTING_BUTTON_CHOICES = (
#     ('Text Decoration', (
#             ('EM',   'Emphasized'),
#             ('I',    'Italic'),
#             ('S',    'Strong'),
#         )
#     ),
#     ('Lists', (
#             ('OL',   'Ordered list'),    
#             ('UL',   'Unordered list'),
#         )
#     ),
#     ('References', (
#         #    ('FN',   'Footnote'),
#             ('IMG',  'Image'),
#             ('URL',  'Linkification'),
#         )
#     ),
#     ('Code', (
#             ('CODE', 'Code'),
#             ('PRE',  'Multi-line code'),
#         )
#     ),
#     ('Quote', 'Block quote'),
# )


def relative_date(date):
    """Displays a date relative to now."""
    delta = datetime.now() - date  # UTC?
    s = delta.seconds
    d = delta.days
    
    if d == 0:
        if s < 60:
            return "Just now"
        elif s < 120:
            return "1 minute ago"
        elif s < 3600:
            s /= 60
            return "%d minutes ago" % s
        elif s < 7200:
            return "1 hour ago"
        elif s < 86400:
            s /= 3600
            return "%d hours ago" % s
    else:
        if d == 1:
            return "Yesterday"
        elif d < 7:
            return "%d days ago" % d
        elif d == 7:
            return "1 week ago"
        elif d/7 < 4:
            d /= 7
            return "%d weeks ago" % d
        elif d/7 == 4:
            return "One month ago"
        else:
            return date


class Category(models.Model):
    """Contains threads."""
    title_plain = models.CharField(max_length=50)
    title_html  = models.TextField()
    #: the sequential placement of categories in the "home"
#   position = models.AutoField(unique=True)
	#: M2M user who has chosen to hide the category in the home view
#   hider = models.ManyToManyField(User, null=True, blank=True
#                                      related_name="hidden_categories")
#    moderators
#    description
#    post_count

    class Meta:
        verbose_name_plural = "categories"
        permissions = (
            ("remove_category", "Remove categories"),
            ("merge_category",  "Merge multiple categories together"),
        )

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/category/%i/" % self.id

    def post_count(self):
        """Shows the number of posts in an entire category."""
        return Post.objects.filter(thread__category = self.id).count()


class Thread(models.Model):
    """Contains posts."""
    creation_date     = models.DateTimeField()
    latest_reply_date = models.DateTimeField()
    author            = models.ForeignKey(User)
    title_plain       = models.CharField(max_length=70)
    title_html        = models.TextField()
    category          = models.ForeignKey(Category)
#   poll              = models.ForeignKey(Poll, null=True, blank=True)    
    bookmarker        = models.ManyToManyField(User, null=True, blank=True,
                                               related_name="bookmarks")
    subscriber        = models.ManyToManyField(User, null=True, blank=True,
                                               related_name="subscriptions")
#    hider            = models.ManyToManyField(User, null=True, blank=True,
#                           related_name="hidden_threads")
    #: Users granted moderator rights on a per-thread basis    
#    threadmins        = models.ManyToManyField(User, null=True, blank=True)
    is_sticky         = models.BooleanField(default=False)
    is_locked         = models.BooleanField(default=False)
    is_removed        = models.BooleanField(default=False)

    class Meta:
        ordering = ["-creation_date"]
        permissions = (
            ("remove_thread",          "Remove threads"),
            ("merge_thread",           "Merge multiple threads together"),
            ("sticky_thread",          "Stick a thread to the top of the thread list"),
            ("move_thread",            "Move a thread to another category"),
            ("lock_thread",            "Lock (and unlock) threads"),
#            ("ban_user_in_thread",     "Ban user from post in thread"),
#            ("timeout_user_in_thread", "Ban user from posting in thread temporarily"),
            ("appoint_threadmin",      "Give a user mod-like permissions in a thread"),
        )

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/thread/%i/" % self.id

    def relative_date(self):
        """Shows the time since the last post in a thread."""
        
        return relative_date(self.latest_reply_date)
    relative_date.short_description = "Latest post"


class Post(models.Model):
    """The reply of a user in a thread. Or its opening post (OP)."""
    creation_date = models.DateTimeField()
    author        = models.ForeignKey(User)
    thread        = models.ForeignKey(Thread)
    content_plain = models.TextField()
    content_html  = models.TextField()
    co_editors    = models.ManyToManyField(User, null=True, blank=True,
                                           verbose_name="co-editor",
                                           related_name="co-editors")
    agrees        = models.ManyToManyField(User, null=True, blank=True,
                                           related_name="agrees")
    thanks        = models.ManyToManyField(User, null=True, blank=True,
                                           related_name="thanks")
    saves         = models.ManyToManyField(User, null=True, blank=True,
                                           related_name="saves")
    is_removed    = models.BooleanField(default=False)

    class Meta:
        ordering = ["creation_date"]
        permissions = (
            ("remove_post", "Can remove posts"),
        )

    def __unicode__(self):
        end = len(self.content_plain) > 40 and "..." or ""
        return u"%s: %s%s" % (self.author, self.content_plain[:40], end)

    def get_absolute_url(self):
        return "/post/%i/" % self.id

    def relative_date(self):
        """Returns the age of the post as a relative date
        between now and creation_date.
        """
        return relative_date(self.creation_date)


class Subscription(models.Model):
    """Manages all the users subscribed to new posts in threads."""
    subscriber     = models.ManyToManyField(User, related_name="subscriber")
    thread         = models.ManyToManyField(Thread, related_name="subscribed_thread")
#    last_read_time = models.DateTimeField(null=True, blank=True)
    last_read_post = models.ManyToManyField(Post, related_name="latest_read_post")

    def __unicode__(self):
        return u"%s's subscription of %s" % (self.subscriber, self.thread.title)


class Report(models.Model):
    """Model for filing reports against the posts and threads of users."""
    creation_date  = models.DateTimeField()
    author         = models.ForeignKey(User, related_name="reporter")
    thread         = models.ForeignKey(Thread, related_name="thread_reports")
    post           = models.ForeignKey(Post, null=True, blank=True,
                                       related_name="post_reports")
    reason_short   = models.CharField(max_length=80)                                
    reason_long    = models.TextField(blank=True)
    was_addressed  = models.BooleanField(default=False)
    addressed_by   = models.ForeignKey(User, null=True, blank=True)
    date_addressed = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["thread", "creation_date"]
        permissions = (
            ("use_reports", "Can see and dismiss reports"),
        )

    def __unicode__(self):
        return u"%s reported something in %s." % (self.author, self.thread)

    def relative_date(self):
        """Shows the time since the last post in a thread."""
        return relative_date(self.creation_date)
    relative_date.short_description = "Latest post"


# Swap the two todisable userena-based accounts (not recommended)
# class UserProfile(models.Model):
class UserProfile(UserenaBaseProfile):
    """Extends the default User model.

    Remember to change your AUTH_PROFILE_MODULE to
    "forum.userprofile" in settings.py to support it.
    """
    user               = models.OneToOneField(User, related_name="profile")
#    avatar_file        = models.ImageField(blank=True,
#                                           upload_to="avatars")
#    avatar_url         = models.URLField(blank=True)
    has_dyslexia       = models.BooleanField(default=False,
                                             verbose_name="User has dyslexia")
    # post_count
    # thread_count
    formatting_buttons = models.BooleanField(default=True)
    #! Automatically subscribe to a thread after posting in it.
    auto_subscribe     = models.BooleanField(default=False,
                                             verbose_name="Automatically subscribe \
                                             to threads posted in")
    # buddies        = models.ManyToManyField(User, null=True, blank=True,
    #                                         related_name="buddies")
    ignores            = models.ManyToManyField(User, null=True, blank=True,
                                                related_name="ignores")
    follows            = models.ManyToManyField(User, null=True, blank=True,

hellodjango/forum/templates/includes/entries.html
                <div class="post" id="{{ post.id }}">
                    {% if post.author == post.thread.author %}
                    <div class="op">
                    {% else %}
                    <div class="user">
                    {% endif %}
                        <span class="username">
                            <a href="/user/{{ post.author.id }}/">{{ post.author.username }}</a>
                        </span>

                        <p class="user-title"></p>
                    <!--
                        <a class="avatar" href="/user/{{ post.author.id }}/">
                            <img src="#" />
                        </a>
                    -->
                        <p>Post{{ post.author.post_set.all|length|pluralize }}: {{ post.author.post_set.all.count }}</p>
                    <!--
                    {% if user.is_authenticated %}
                        <p><a href="#">Send PM</a></p>
                    {% endif %}
                    -->
                    </div>
                    <div class="words">
                        <div class="post-top">
                            <span class="postdate">{{ post.relative_date }}</span>
                            <!-- Anchor number borked -->
                            <a class="anchor" href="/thread/{{ post.thread.id }}/#{{ post.id }}">#</a>
                            <a class="permalink" title="View this post by itself at its own link" href="/post/{{ post.id }}/">&infin;</a>
                            <a class="postsinthread" title="View all posts by the {{ post.author.username }} in this thread" href="/thread/{{ thread.id }}/author/{{ post.author.id }}/">&Phi;</a>
                        </div>
                        <div class="body">{{ post.content_html|safe }}</div>
                    </div>
                    <div class="post-bottom">
                        <div class="right-buttons">
                        {% if not post.thread.is_locked %}
                            <a class="button" href="/thread/{{ post.thread.id }}/reply">Reply</a>
                        {% endif %}
                    {% if user.is_authenticated %}
                        {% if user == post.author %}
                            <a class="button" href="/post/{{ post.id }}/edit/">Edit</a>
                        {% endif %}
                        {% if user == post.author and forloop.first %}
                            <a class="button" href="/thread/{{ thread.id }}/co-editor">Manage Co-Editors</a>
                        {% endif %}
                    {% endif %}
                        </div>

                        <div class="left-buttons">
                            <a class="button js" id="{{ post.id }}" href="#">{% if post in user.saves.all %}Unsave{% else %}Save{% endif %}</a>
                        {% if user != post.author %}
                            <a class="button js" id="{{ post.id }}" href="#">{% if post in user.thanks.all %}Unthank{% else %}Thank{% endif %}</a>
                            <a class="button js" id="{{ post.id }}" href="#">{% if post in user.agrees.all %}Unagree{% else %}Agree{% endif %}</a>
                        {% endif %}
                        {% if post.thanks.all %}
                            <a class="button thanks" href="#">Thanked</a>
                        {% endif %}
                        {% if post.agrees.all %}
                            <a class="button agrees" href="#">Has Agrees</a>
                        {% endif %}
                    {% if user != post.author %}
                        {% if not post.thread.is_locked %}
                            <a class="button" id="{{ post.id }}" href="{{ post.get_absolute_url }}report">Report</a>
                        {% endif %}
                    {% endif %}
                        {% if perms.forum.remove_post %}
                            <a class="button" href="{{ post.get_absolute_url }}remove">Remove</a>
                        {% endif %}
                        </div>

                {# Three cases: 1) The first person 2) Everyone between 3) The last person #}
                    {% if post.thanks.all %}
                        <div class="thankers">Thanked by: <i>{% for person in post.thanks.all %}{% if forloop.first and not forloop.last %}<a href="/user/{{ person.id }}" title="See the people who have thanked the author for this post">{{ person.username }}</a>{% endif %}{% if not forloop.first and not forloop.last %}<a href="/user/{{ person.id }}" title="See the people who have thanked the author for this post">{{ person.username }}, </a>{% endif %}{% if forloop.last and not forloop.first %}and <a href="/user/{{ person.id }}" title="See the people who have thanked the author for this post">{{ person.username }}</a>{% endif %}<a href="/user/{{ person.id }}" title="See the people who have thanked the author for this post">{{ person.username }}</a>{% endfor %}.</i></div>
                    {% endif %}
                    {% if post.agrees.all %}
                        <div class="agreeers">These people agree: <i>{% for person in post.thanks.all %}{% if forloop.first and not forloop.last %}<a href="/user/{{ person.id }}" title="See the people who agreed with this post">{{ person.username }}</a>{% endif %}{% if not forloop.first and not forloop.last %}<a href="/user/{{ person.id }}" title="See the people who agreed with this post">{{ person.username }}, </a>{% endif %}{% if forloop.last and not forloop.first %}and <a href="/user/{{ person.id }}" title="See the people who agreed with this post">{{ person.username }}</a>{% endif %}<a href="/user/{{ person.id }}" title="See the people who agreed with this post">{{ person.username }}</a>{% endfor %}.</i></div>
                    {% endif %}
                    </div>
                </div>

hellodjango/forum/templates/includes/js-blocked-warning.html
            <div id="js-blocked-warning">
                JavaScript is currently disabled in your browser. This means that you will not be able to <code>subscribe</code> and <code>bookmark</code>, <code>thank</code>, <code>save</code>, and <code>agree</code>.
            </div>

hellodjango/forum/templates/includes/markdown.html
                <div id="markdown">
                    <table>
                        <tr>
                            <th>Markdown(<a class="markdown-guide" href="http://daringfireball.net/projects/markdown/basics">?</a>) code</th>
                            <th>Formatting result</th>
                        <tr>
                        <tr>
                            <td>*Strong* text</td>
                            <td><strong>Strong</strong> text</td>
                        </tr>
                        <tr>
                            <td>**Emphasized** text</td>
                            <td><em>Emphasized</em> text</td>
                        </tr>
                        <tr>
                            <td>`Code`</td>
                            <td><code>Code</code></td>
                        </tr>
                        <tr>
                            <td>&gt;Quoted text</td>
                            <td><blockquote>Quoted text</blockquote></td>
                        </tr>
                        <tr>
                            <td>
                                <p>&gt;Block quote</p>
                                <p>&gt;</p>
                                <p>&gt;On several lines</p>
                            </td>
                            <td>
                                <blockquote>
                                    <p>Block quote</p>
                                    
                                    <p>On several lines</p>
                                </blockquote>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                &lt;blockquote&gt;<br />
                                <p>Block quote</p>
                                
                                <p>On several lines</p>
                                &lt;/blockquote&gt;
                            </td>
                            <td>
                                <blockquote>
                                    <p>Block quote</p>
                                    <p></p>
                                    <p>On several lines</p>
                                </blockquote>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>&gt;Block quote</p>
                                <p>&gt;&gt;Nested quote</p>
                                <p>&gt;On several lines</p>
                            </td>
                            <td>
                                <blockquote>
                                    <p>Block quote</p>
                                    <blockquote><p>Nested quote</p></blockquote>
                                    <p>On several lines</p>
                                </blockquote>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                &lt;blockquote&gt;<br />
                                <p>Block quote</p>
                                &lt;blockquote&gt;<p>Nested quote</p>&lt;/blockquote&gt;
                                <p>On several lines</p>
                                &lt;/blockquote&gt;
                            </td>
                            <td>
                                <blockquote>
                                    <p>Block quote</p>
                                    <blockquote><p>Nested quote</p></blockquote>
                                    <p>On several lines</p>
                                </blockquote>
                            </td>
                        </tr>
                        <tr>
                            <td>Text&lt;sub&gt;subscript&lt;/sub&gt;</td>
                            <td>Text<sub>subscript</sub></td>
                        </tr>
                        <tr>
                            <td>Text&lt;sup&gt;superscript&lt;/sup&gt;</td>
                            <td>Text<sup>superscript</sup></td>
                        </tr>
                        <tr>
                            <td>[Link](http://example.com)</td>
                            <td><a href="http://example.com">Link</a></td>
                        </tr>
                        <tr>
                            <td>
                                <p>[Another link][linkname]</p>
                                <p>&hellip;</p>
                                <p>[linkname]: http://example.com</p>
                            </td>
                            <td><a href="http://example.com">Another link</a></td>
                        </tr>
                        <tr>
                            <td>![alt text](http://example.com/image.png)</td>
                            <td>(Imagine an image with alt text &ldquo;alt text&rdquo; here.)</a></td>
                        </tr>
                        <tr>
                            <td>
                                <p>![alt text][imgname]</p>
                                <p>&hellip;</p>
                                <p>[imgname]: http://example.com/image.png)</p>
                            </td>
                            <td>(Imagine the same image and alt text.)</a></td>
                        </tr>
                        <tr>
                            <td>1. Ordered list</td>
                            <td><ol><li>Ordered list</li></ol></td>
                        </tr>
                        <tr>
                            <td>* Unordered list</td>
                            <td><ul><li>Unordered list</li></ul></td>
                        </tr>
                        <tr>
                            <td>
                                * Unorderd list with a<br />
                                &nbsp;&nbsp;&nbsp;&nbsp;1. Nested list made with an indentation
                            </td>
                            <td>
                                <ul>
                                    <li>Unordered list</li>
                                    <ol>
                                        <li>Nested list made with an indentation</li>
                                    </ul>
                                </ul>
                            </td>
                        </tr>
                        <!--
                        <tr>
                            <td>Footnotes</td>
                            <td>(Read <a href="http://www.freewisdom.org/projects/python-markdown/Footnotes">this</a> guide.)</td>
                        </tr>
                        -->
                        <tr>
                            <td>Tables</td>
                            <td>(Read <a href="http://www.freewisdom.org/projects/python-markdown/Tables">this</a> guide.</td>
                        </tr>
                    </table>
                </div>

hellodjango/forum/templates/includes/threadbar.html
            <div id="threadbar">
            {% if subs %}
                <div id="subscribed">
                <span class="threadsort">Subscribed Threads</span>
                    <ul>      
                    {% for sub in subs %}
                        <li><a href="/thread/{{ sub.id }}/" title="View the posts in the thread &ldquo;{{ sub.title_html|safe }}&rdquo;">{{ sub.title_html|safe }}</a>{% if update %} <span class="updates">{{ update.count }}</span></a>{% endif %}</li>
                    {% endfor %}                 
                    </ul>
                </div>
            {% endif %}
                <div id="recent">
                <span class="threadsort">New Threads</span>
                    <ul>
                    {% for thread in new_threads %}
                        <li><a href="/thread/{{ thread.id }}/" title="View the posts in the thread &ldquo;{{ thread.title_html|safe }}&rdquo;">{{ thread.title_html|safe }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            <!--
                <div id="popular">
                <span class="threadsort">Popular Threads</span>
                    <ul>
                        <li><a href="#">Recommend a Movie</span></a></li>
                    </ul>
                </div>
            -->
            </div>