hellodjango/urls.py
from django.conf.urls.defaults   import patterns, include, url
from django.contrib              import admin
from django.views.generic.simple import redirect_to

from userena                     import views as userena_views

admin.autodiscover()

urlpatterns = patterns('forum.views',
    (r'^$',                                      'home'),
    (r'^reports/$',                              'reports'),
#   (r'^search/$',                               'search'),
    (r'^subscriptions/$',                        'subscriptions'),

#   Category
    (r'^category/add/$',                         'add'),
    (r'^category/(?P<category_id>\d+)/create/$', 'create'),
#   (r'^category/(?P<category_id>\d+)/merge/$',  'merge'),
    (r'^category/(?P<category_id>\d+)/$',        'category'),

#   Thread
    (r'^thread/(?P<thread_id>\d+)/reply/$',      'reply'),
    (r'^thread/js/$',                            'thread_js'),
    (r'^thread/(?P<thread_id>\d+)/lock/$',       'lock_thread'),
    (r'^thread/(?P<thread_id>\d+)/sticky/$',     'sticky_thread'),
    (r'^thread/(?P<thread_id>\d+)/merge/$',      'merge_thread'),
    (r'^thread/(?P<thread_id>\d+)/move/$',       'move_thread'),
    (r'^thread/(?P<thread_id>\d+)/moderate/$',   'moderate_thread'),
    (r'^thread/(\d+)/report/$',                  'report',
                                                 	 {'object_type': 'thread'}),
    (r'^thread/(\d+)/remove/$',                  'remove',
                                                     {'object_type': 'thread'}),
    (r'^thread/(?P<thread_id>\d+)/$',            'thread',
                                                     {'author_id': "Everyone"}),
	(r'^thread/(?P<thread_id>\d+)/author/(?P<author_id>\d+)/$', 'thread'),

#   Post
    (r'^post/(?P<post_id>\d+)/edit/$',           'edit'),
    (r'^post/(\d+)/report/$',                    'report',
                                                     {'object_type': 'post'}),
    (r'^post/(\d+)/remove/$',                    'remove',
                                                     {'object_type': 'post'}),
    (r'^post/(?P<post_id>\d+)/$',                'post'),

#   User
    (r'^user/js/$',                              'user_js'),
    (r'^user/(?P<user_id>\d+)/threads/$',        'user_content', 
                                                     {'object_type': 'thread'}),
    (r'^user/(?P<user_id>\d+)/posts/$',          'user_content',
                                                     {'object_type': 'post'}),
    (r'^user/(?P<user_id>\d+)/$',                'user'),

#   Accounts
#   (r'^login/$',                                'login'),
#   (r'^logout/$',                               'logout'), 
#   (r'^signup/$',                               'register'),
#	(r'^settings/$',                             'settings'),

    # Redirecting undesired URLs in the userena app to home page
    # and replacing them with such ones as "login" and "logout".
    #
    # <?Pdummy> is there to capture the argument that should not 
    # be passed to the url of redirect_to().
    #
    # Kinda hacky, but gets it done.
    (r'^accounts/login/$',                        userena_views.signin),
    (r'^accounts/logout/$',                      'logout'),
    (r'^accounts/settings/$',                    'settings'),

    url(r'^accounts/$',
        redirect_to, {'url': '/'}),

    url(r'^accounts/signin/$',
        redirect_to, {'url': '/accounts/login/'}),

    url(r'^accounts/signout/$',
        redirect_to, {'url': '/accounts/logout/'}),

    url(r'^accounts/page/(?P<dummy>[0-9]+)/$',
        redirect_to, {'url': '/'}),

    url(r'^accounts/(?P<dummy>(?!login|logout|signup)[\.\w]+)/edit/$',
        redirect_to, {'url': '/'}),

    url(r'^accounts/(?P<dummy>(?!login|logout|signup)[\.\w]+)/$',
        redirect_to, {'url': '/'}),
)

urlpatterns += patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/',     include(admin.site.urls)),
    url(r'^accounts/',  include('userena.urls')),
)

hellodjango/forum/models.py
from datetime                   import datetime

from django.contrib.auth.models	import User
from django.db					import models
from django.db.models.signals   import post_save

from userena.models             import UserenaBaseProfile


# Accessed by UserProfile.get_formatting_buttons_display()
# minus the () for a template
# 
# FORMATTING_BUTTON_CHOICES = (
#     ('Text Decoration', (
#             ('EM',   'Emphasized'),
#             ('I',    'Italic'),
#             ('S',    'Strong'),
#         )
#     ),
#     ('Lists', (
#             ('OL',   'Ordered list'),    
#             ('UL',   'Unordered list'),
#         )
#     ),
#     ('References', (
#         #    ('FN',   'Footnote'),
#             ('IMG',  'Image'),
#             ('URL',  'Linkification'),
#         )
#     ),
#     ('Code', (
#             ('CODE', 'Code'),
#             ('PRE',  'Multi-line code'),
#         )
#     ),
#     ('Quote', 'Block quote'),
# )


def relative_date(date):
    """Displays a date relative to now."""
    delta = datetime.now() - date  # UTC?
    s = delta.seconds
    d = delta.days
    
    if d == 0:
        if s < 60:
            return "Just now"
        elif s < 120:
            return "1 minute ago"
        elif s < 3600:
            s /= 60
            return "%d minutes ago" % s
        elif s < 7200:
            return "1 hour ago"
        elif s < 86400:
            s /= 3600
            return "%d hours ago" % s
    else:
        if d == 1:
            return "Yesterday"
        elif d < 7:
            return "%d days ago" % d
        elif d == 7:
            return "1 week ago"
        elif d/7 < 4:
            d /= 7
            return "%d weeks ago" % d
        elif d/7 == 4:
            return "One month ago"
        else:
            return date


class Category(models.Model):
    """Contains threads."""
    title_plain = models.CharField(max_length=50)
    title_html  = models.TextField()
    #: the sequential placement of categories in the "home"
#   position = models.AutoField(unique=True)
	#: M2M user who has chosen to hide the category in the home view
#   hider = models.ManyToManyField(User, null=True, blank=True
#                                      related_name="hidden_categories")
#    moderators
#    description
#    post_count

    class Meta:
        verbose_name_plural = "categories"
        permissions = (
            ("remove_category", "Remove categories"),
            ("merge_category",  "Merge multiple categories together"),
        )

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/category/%i/" % self.id

    def post_count(self):
        """Shows the number of posts in an entire category."""
        return Post.objects.filter(thread__category = self.id).count()


class Thread(models.Model):
    """Contains posts."""
    creation_date     = models.DateTimeField()
    latest_reply_date = models.DateTimeField()
    author            = models.ForeignKey(User)
    title_plain       = models.CharField(max_length=70)
    title_html        = models.TextField()
    category          = models.ForeignKey(Category)
#   poll              = models.ForeignKey(Poll, null=True, blank=True)    
    bookmarker        = models.ManyToManyField(User, null=True, blank=True,
                                               related_name="bookmarks")
    subscriber        = models.ManyToManyField(User, null=True, blank=True,
                                               related_name="subscriptions")
#    hider            = models.ManyToManyField(User, null=True, blank=True,
#                           related_name="hidden_threads")
    #: Users granted moderator rights on a per-thread basis    
#    threadmins        = models.ManyToManyField(User, null=True, blank=True)
    is_sticky         = models.BooleanField(default=False)
    is_locked         = models.BooleanField(default=False)
    is_removed        = models.BooleanField(default=False)

    class Meta:
        ordering = ["-creation_date"]
        permissions = (
            ("remove_thread",          "Remove threads"),
            ("merge_thread",           "Merge multiple threads together"),
            ("sticky_thread",          "Stick a thread to the top of the thread list"),
            ("move_thread",            "Move a thread to another category"),
            ("lock_thread",            "Lock (and unlock) threads"),
#            ("ban_user_in_thread",     "Ban user from post in thread"),
#            ("timeout_user_in_thread", "Ban user from posting in thread temporarily"),
            ("appoint_threadmin",      "Give a user mod-like permissions in a thread"),
        )

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/thread/%i/" % self.id

    def relative_date(self):
        """Shows the time since the last post in a thread."""
        
        return relative_date(self.latest_reply_date)
    relative_date.short_description = "Latest post"


class Post(models.Model):
    """The reply of a user in a thread. Or its opening post (OP)."""
    creation_date = models.DateTimeField()
    author        = models.ForeignKey(User)
    thread        = models.ForeignKey(Thread)
    content_plain = models.TextField()
    content_html  = models.TextField()
    co_editors    = models.ManyToManyField(User, null=True, blank=True,
                                           verbose_name="co-editor",
                                           related_name="co-editors")
    agrees        = models.ManyToManyField(User, null=True, blank=True,
                                           related_name="agrees")
    thanks        = models.ManyToManyField(User, null=True, blank=True,
                                           related_name="thanks")
    saves         = models.ManyToManyField(User, null=True, blank=True,
                                           related_name="saves")
    is_removed    = models.BooleanField(default=False)

    class Meta:
        ordering = ["creation_date"]
        permissions = (
            ("remove_post", "Can remove posts"),
        )

    def __unicode__(self):
        end = len(self.content_plain) > 40 and "..." or ""
        return u"%s: %s%s" % (self.author, self.content_plain[:40], end)

    def get_absolute_url(self):
        return "/post/%i/" % self.id

    def relative_date(self):
        """Returns the age of the post as a relative date
        between now and creation_date.
        """
        return relative_date(self.creation_date)


class Subscription(models.Model):
    """Manages all the users subscribed to new posts in threads."""
    subscriber     = models.ManyToManyField(User, related_name="subscriber")
    thread         = models.ManyToManyField(Thread, related_name="subscribed_thread")
#    last_read_time = models.DateTimeField(null=True, blank=True)
    last_read_post = models.ManyToManyField(Post, related_name="latest_read_post")

    def __unicode__(self):
        return u"%s's subscription of %s" % (self.subscriber, self.thread.title)


class Report(models.Model):
    """Model for filing reports against the posts and threads of users."""
    creation_date  = models.DateTimeField()
    author         = models.ForeignKey(User, related_name="reporter")
    thread         = models.ForeignKey(Thread, related_name="thread_reports")
    post           = models.ForeignKey(Post, null=True, blank=True,
                                       related_name="post_reports")
    reason_short   = models.CharField(max_length=80)                                
    reason_long    = models.TextField(blank=True)
    was_addressed  = models.BooleanField(default=False)
    addressed_by   = models.ForeignKey(User, null=True, blank=True)
    date_addressed = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["thread", "creation_date"]
        permissions = (
            ("use_reports", "Can see and dismiss reports"),
        )

    def __unicode__(self):
        return u"%s reported something in %s." % (self.author, self.thread)

    def relative_date(self):
        """Shows the time since the last post in a thread."""
        return relative_date(self.creation_date)
    relative_date.short_description = "Latest post"


# Swap the two todisable userena-based accounts (not recommended)
# class UserProfile(models.Model):
class UserProfile(UserenaBaseProfile):
    """Extends the default User model.

    Remember to change your AUTH_PROFILE_MODULE to
    "forum.userprofile" in settings.py to support it.
    """
    user               = models.OneToOneField(User, related_name="profile")
#    avatar_file        = models.ImageField(blank=True,
#                                           upload_to="avatars")
#    avatar_url         = models.URLField(blank=True)
    has_dyslexia       = models.BooleanField(default=False,
                                             verbose_name="User has dyslexia")
    # post_count
    # thread_count
    formatting_buttons = models.BooleanField(default=True)
    #! Automatically subscribe to a thread after posting in it.
    auto_subscribe     = models.BooleanField(default=False,
                                             verbose_name="Automatically subscribe \
                                             to threads posted in")
    # buddies        = models.ManyToManyField(User, null=True, blank=True,
    #                                         related_name="buddies")
    ignores            = models.ManyToManyField(User, null=True, blank=True,
                                                related_name="ignores")
    follows            = models.ManyToManyField(User, null=True, blank=True,

hellodjango/forum/templates/add.html
{% extends "base.html" %}

{% block title %}Category creation station{% endblock %}
{% block content %}
            <div id="board">

                {% if has_long_title %}
                    Your chosen title was too long. Keep it under {{ max_title_length }} characters.
                {% endif %}

                <form action="/category/add/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}
                    <input type="text" name="title" id="title-form" value="{% if title %}{{ title }}{% endif %}" placeholder="Put your title here (in capital letters). Keep it less than eighty characters." autofocus required />
                    
                    <input type="submit" name="submit" id="submit" value="Add" />
                </form>
            </div>
{% endblock %}

hellodjango/forum/templates/create.html
{% extends "base.html" %}

{% block title %}Create new thread in {{ category.title_html|safe }}{% endblock %}
{% block canonical_url %}{{ category.get_absolute_url }}create/{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ category.id }}/">{{ category.title_html|safe }}</a>
                </div>

        {% if preview_html %}
                <div id="example">
                    {{ preview_html|safe }}
                </div>
        {% endif %}

                <form action="{{ category.get_absolute_url }}create/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}
                    <input type="text" name="title" id="title-form" value="{% if title %}{{ title }}{% endif %}" placeholder="Put your title here (in capital letters). Keep it less than eighty characters, and be descriptive." required />
                    <textarea
                        rows="10" name="content" placeholder="Write the content of your post here, use the Markdown formatting explained below, and press &ldquo;Reply&rdquo;." autofocus required>{% if preview_plain %}{{ preview_plain }}{% endif %}</textarea>
                    
                    <input type="submit" name="submit" id="submit" value="Create" />
                    <input type="submit" name="preview" id="preview" value="Preview" />
                </form>

                {% include "includes/markdown.html" %}
            </div>
{% endblock %}

hellodjango/forum/templates/edit.html
{% extends "base.html" %}

{% block title %}{{ post.thread.title_html|safe }}: Edit Post{% endblock %}
{% block canonical_url %}{{ post.get_absolute_url }}edit/{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ post.thread.category.id }}/">{{ post.thread.category.title_html|safe }}</a>&nbsp;&raquo;&nbsp;<a href="/thread/{{ post.thread.id }}/">{{ post.thread.title_html|safe }}</a>{% if type == "post" %}&nbsp;&raquo;&nbsp;<a href="{{ obj.get_absolute_url }}">{{ obj.author }}&rsquo;s Post</a>{% endif %}
                </div>

            {% if preview_html %}
                <div id="example">
                    {{ preview_html|safe }}
                </div>
            {% endif %}

                <form action="{{ post.get_absolute_url }}edit/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}
                    <textarea
                        rows="10" name="content" placeholder="Write the content of your post here, use the Markdown formatting explained below, and press &ldquo;Reply&rdquo;." autofocus required>{% if preview_plain %}{{ preview_plain }}{% else %}{{ post.content_plain }}{% endif %}</textarea>
                    
                    <input type="submit" name="submit" id="submit" value="Edit" />
                    <input type="submit" name="preview" id="preview" value="Preview" />
                </form>

                {% include "íncludes/markdown.html" %}
            </div>
{% endblock %}

hellodjango/forum/templates/lock.html
{% extends "base.html" %}

{% block title %}{{ thread.title_html|safe }}: Lock and Unlock{% endblock %}
{% block canonical_url %}{{ thread.get_absolute_url }}lock/{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ thread.category.id }}/">{{ thread.category.title_html|safe }}</a>&nbsp;&raquo;&nbsp;<a href="{{ thread.get_absolute_url }}">{{ thread.title_html|safe }}</a>
                </div>

                <form action="{{ thread.get_absolute_url }}lock/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}
                    
                    <input type="submit" name="lock" value="Lock" />
                    <input type="submit" name="unlock" value="Unlock" />
                </form>
            </div>
{% endblock %}

hellodjango/forum/templates/merge.html
{% extends "base.html" %}

{% block title %}{{ thread.title_html|safe }}: Merge Threads{% endblock %}
{% block canonical_url %}{{ thread.get_absolute_url }}merge/{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ thread.category.id }}/">{{ thread.category.title_html|safe }}</a>&nbsp;&raquo;&nbsp;<a href="/thread/{{ thread.id }}/">{{ thread.title_html|safe }}</a>
                </div>

            {% if has_long_title %}
                <p>Your chosen title was too long. Keep it under {{ max_title_length }} characters.</p>
            {% endif %}

            {% if not other_thread and not has_long_title %}
                <form action="{{ thread.get_absolute_url }}merge/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}

                    <input type="number" name="other-thread-id" id="id-form" value="{% if other_thread %}{{ other_thread.id }}{% endif %}" min="1" step="1" placeholder="Enter the ID of the other thread." required />

                    <input type="text" name="new-thread-title" id="title-form" value="{{ new_title }}" placeholder="Put your title here (in capital letters). Keep it less than eighty characters, and be descriptive." required />
                    
                    <input type="submit" name="merge" id="submit" value="Merge" />
                </form>
            {% else %}
                <form action="{{ thread.get_absolute_url }}merge/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}

                    <p>Are you sure, you want to merge these threads:</p>
                    <ul>
                        <li><i>{{ thread.title_html|safe }}</i></li>
                        <li><i>{{ other_thread.title_html|safe }}</i></li>
                    </ul>
                    <p>Merging them will show the posts in both in chronological order in one single thread named <i>{{ new_title_html|safe }}</i>.</p>
                    
                    <input type="submit" name="confirm" id="submit" value="Yes, merge them" />
                    <input type="submit" name="cancel" id="submit" value="Cancel" />

                    <input type="hidden" name="other-thread-id" value="{{ other_thread.id }}" />
                    <input type="hidden" name="new-thread-title" value="{{ new_title }}" />
                </form>
            {% endif %}
            </div>
{% endblock %}

hellodjango/forum/templates/moderate.html
{% extends "base.html" %}

{% block title %}{{ thread.title_html|safe }}: Moderate Thread{% endblock %}
{% block canonical_url %}{{ thread.get_absolute_url }}moderate/{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ thread.category.id }}/">{{ thread.category.title_html|safe }}</a>&nbsp;&raquo;&nbsp;<a href="/thread/{{ thread.id }}/">{{ thread.title_html|safe }}</a>
                </div>

                {% if has_long_title %}
                    Your chosen title was too long. Keep it under characters.
                {% endif %}

                <form action="{{ thread.get_absolute_url }}moderate/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}
                    <input type="text" name="title" id="title-form" value="{{ title }}" placeholder="Put your title here (in capital letters). Keep it less than eighty characters, and be descriptive." required />
                    
                    <input type="submit" name="moderate" id="submit" value="Moderate" />
                </form>
            </div>
{% endblock %}

hellodjango/forum/templates/move.html
{% extends "base.html" %}

{% block title %}{{ thread.title_html|safe }}: Move Thread{% endblock %}
{% block canonical_url %}{{ thread.get_absolute_url }}move/{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ thread.category.id }}/">{{ thread.category.title_html|safe }}</a>&nbsp;&raquo;&nbsp;<a href="{{ thread.get_absolute_url }}">{{ thread.title_html|safe }}</a>
                </div>

                <form action="{{ thread.get_absolute_url }}move/" method="post" id="reply" name="reply-form">
                    {% csrf_token %}
                    
                {% for category in categories %}
                    <input type="radio" name="category" value="{{ category.id }}" {% if category == thread.category %}checked{% endif %} />{{ category.title_html|safe }}<br />
                {% endfor %}

                <input type="submit" name="move" value="Move" />
                </form>
            </div>
{% endblock %}

hellodjango/forum/templates/post.html
{% extends "base.html" %}

{% block title %}{{ post.thread.title_html|safe }}: Post #{{ anchor_number }} by {{ post.author }}{% endblock %}
{% block canonical_url %}{{ post.get_absolute_url }}{% endblock %}
{% block js-blocked-warning %}{% include "includes/js-blocked-warning.html" %}{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ post.thread.category.id }}/">{{ post.thread.category.title_html }}</a>&nbsp;&raquo;&nbsp;<a href="/thread/{{ post.thread.id }}/">{{ post.thread.title_html }}{% if post.thread.is_locked %}&nbsp;(LOCKED){% endif %}</a>{% if type == "post" %}&nbsp;&raquo;&nbsp;<a href="{{ obj.get_absolute_url }}">{{ obj.author }}&rsquo;s Post</a>{% endif %}
                </div>

                {% include "includes/entries.html" %}

            </div>
{% endblock %}
{% block js %}
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/thread-js.js"></script>
{% endblock %}

hellodjango/forum/templates/thread.html
{% extends "base.html" %}

{% block title %}{{ thread.title_html|safe }}{% if thread.is_locked %}&nbsp;(LOCKED){% endif %}{% endblock %}
{% block canonical_url %}{{ thread.get_absolute_url }}{% endblock %}
{% block js-blocked-warning %}{% include "includes/js-blocked-warning.html" %}{% endblock %}
{% block content %}
            <div id="board">
                <div id="breadcrumbs">
                    <a href="/">Overview</a>&nbsp;&raquo;&nbsp;<a href="/category/{{ thread.category.id }}/">{{ thread.category.title_html|safe }}</a>&nbsp;&raquo;&nbsp;<a href="{{ thread.get_absolute_url }}">{{ thread.title_html|safe }}{% if thread.is_locked %}&nbsp;(LOCKED){% endif %}</a>
                </div>
        
        <!--    <div class="pagination"></div> -->

            {% if not thread.is_removed %}
                <div id="thread-buttons-top">
                {% if not thread.is_locked %}
                    <a class="button" href="{{ thread.get_absolute_url }}reply">
                    Reply</a>
                    <a class="button" href="{{ thread.get_absolute_url }}report">Report</a>
                {% else %}
                    <a class="button" href="#">Locked</a>
                {% endif %}
                    <a class="button js" id="{{ thread.id }}" href="#">{% if thread in user.bookmarks.all %}Unbookmark{% else %}Bookmark{% endif %}</a>
                    <a class="button js" id="{{ thread.id }}" href="#">{% if thread in user.subscriptions.all %}Unsubscribe{% else %}Subscribe{% endif %}</a>
                </div>
            {% endif %}

                <div id="thread-mod-buttons-top">
            {% if thread.is_removed and perms.forum.remove_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}remove/">Restore</a>
            {% else %}
                {% if perms.forum.lock_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}lock/">{% if thread.is_locked %}Unlock{% else %}Lock{% endif %}</a>
                {% endif %}
                {% if perms.forum.change_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}moderate/">Moderate</a>
                {% endif %}
                {% if perms.forum.move_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}move/">Move</a>
                {% endif %}
                {% if perms.forum.sticky_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}sticky/">{% if thread.is_sticky %}Unsticky{% else %}Sticky{% endif %}</a>
                {% endif %}
                {% if perms.forum.merge_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}merge/">Merge</a>
                {% endif %}
                {% if perms.forum.remove_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}remove/">Remove</a>
                {% endif %}
            {% endif %}
                <!-- appoint_threadmin -->
                </div>

            {% for post in posts %} <!-- exclude is_removed -->
                {% include "includes/entries.html" %}
            {% endfor %}

                <div id="thread-mod-buttons-bottom">
            {% if thread.is_removed and perms.forum.remove_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}remove/">Restore</a>
            {% else %}
                {% if perms.forum.lock_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}lock/">{% if thread.is_locked %}Unlock{% else %}Lock{% endif %}</a>
                {% endif %}
                {% if perms.forum.change_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}moderate/">Moderate</a>
                {% endif %}
                {% if perms.forum.move_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}move/">Move</a>
                {% endif %}
                {% if perms.forum.sticky_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}sticky/">{% if thread.is_sticky %}Unsticky{% else %}Sticky{% endif %}</a>
                {% endif %}
                {% if perms.forum.merge_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}merge/">Merge</a>
                {% endif %}
                {% if perms.forum.remove_thread %}
                    <a class="button" href="{{ thread.get_absolute_url }}remove/">Remove</a>
                {% endif %}
            {% endif %}
                <!-- appoint_threadmin -->
                </div>

            {% if not thread.is_removed %}
                <div id="thread-buttons-bottom">
                {% if not thread.is_locked %}
                    <a class="button" href="{{ thread.get_absolute_url }}reply">
                    Reply</a>
                    <a class="button" href="{{ thread.get_absolute_url }}report">Report</a>
                {% else %}
                    <a class="button" href="#">Locked</a>
                {% endif %}
                    <a class="button js" id="{{ thread.id }}" href="#">{% if thread in user.bookmarks.all %}Unbookmark{% else %}Bookmark{% endif %}</a>
                    <a class="button js" id="{{ thread.id }}" href="#">{% if thread in user.subscriptions.all %}Unsubscribe{% else %}Subscribe{% endif %}</a>
                </div>
            {% endif %}

        <!--    <div class="pagination"></div> -->
            </div>
{% endblock %}
{% block js %}
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/thread-js.js"></script>
{% endblock %}